export { resolveOptions } from './resolveOptions'
export type { Dependencies } from './resolveDependencies'
export type { Extensions } from './resolveExtensions'
export type { Has } from './resolveHas'
export type { PackageJson } from './resolvePackageJson'
export type { Paths } from './resolvePaths'
export type { Prettier } from './resolvePrettier'
export type { ResolvedUserOptions, UserOptions } from './resolveUserOptions'
export type { DefinedOptions, Options } from './types'
